kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: greeting
spec:
  hosts:
    - '*'
  gateways:
    - greeting-gateway
  http:
    - match:
        - uri:
            prefix: /greeting
      route:
        - destination:
            host: greeting
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: greeting
spec:
  host: greeting
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - labels:
        version: v1
      name: v1
---
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: greeting-gateway
spec:
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway
